/*
 * NodeProf Analysis Script for Prototype Pollution in dset.js
 *
 * This script intercepts key JavaScript operations to trace the data flow
 * that leads to the prototype pollution vulnerability.
 */
((sandbox) => {
    // A simple mechanism to assign a unique ID to each object for easier tracking.
    const objectIdMap = new WeakMap();
    let objectIdCounter = 1;
    function getObjectId(obj) {
        if (!obj || (typeof obj !== 'object' && typeof obj !== 'function')) {
            return `[primitive: ${typeof obj}]`;
        }
        if (!objectIdMap.has(obj)) {
            objectIdMap.set(obj, objectIdCounter++);
        }
        return `obj_id_${objectIdMap.get(obj)}`;
    }
    
    // ---- Analysis State ----
    // This variable will store the array of keys generated by `keys.split('.')`.
    // We "taint" this array to track its usage.
    let taintedKeysArray = null;
    let originalPollutingString = "";

    class DsetPollutionAnalysis {
        
        /**
         * Called after a function is invoked. We use this to capture the result of `keys.split('.')`.
         * @param {number} iid - Unique instruction identifier.
         * @param {function} f - The function that was called.
         * @param {object} base - The `this` object for the call.
         * @param {Array} args - The arguments passed to the function.
         * @param {*} result - The value returned by the function.
         * @param {boolean} isConstructor - True if the call was a constructor.
         * @returns {{result: *}} - Potentially modified result.
         */
        invokeFun(iid, f, base, args, result, isConstructor) {
            // Check if this is the 'split' function we are interested in.
            if (f === String.prototype.split && args[0] === '.' && typeof base === 'string' && base.includes('__proto__')) {
                console.log(`[+] Taint Source Identified: String.prototype.split called on "${base}"`);
                console.log(`    - Resulting array: [${result.map(v => `'${v}'`).join(', ')}]`);
                console.log(`    - Assigning taint to result object: ${getObjectId(result)}`);
                
                // Mark the resulting array as tainted.
                taintedKeysArray = result;
                originalPollutingString = base;
            }
            return { result: result };
        }

        /**
         * Called before a property of an object is written to (e.g., obj[prop] = val).
         * This is the sink of our analysis, where the pollution actually happens.
         * @param {number} iid - Unique instruction identifier.
         * @param {object} base - The object whose property is being set.
         * @param {(string|Symbol)} offset - The name of the property being set.
         * @param {*} val - The value being assigned.
         * @returns {{base: *, offset: *, val: *}} - Potentially modified values.
         */
        putFieldPre(iid, base, offset, val) {
            // Check if the property access is part of the dset loop
            // by checking if the 'keys' variable in dset.js is our tainted array.
            // In dset.js, the loop is `t = t[keys[i]] = ...`, where `t` is the `base`.
            // The `offset` is one of the keys from our tainted array.
            
            if (taintedKeysArray && taintedKeysArray.includes(offset)) {
                
                const baseId = getObjectId(base);
                let baseName = "";
                // The most critical check: are we writing to the Object.prototype?
                if (base === Object.prototype) {
                    baseName = " (!!! Object.prototype !!!)";
                }

                console.log(`[+] Tainted Write Detected:`);
                console.log(`    - Target Object: ${baseId}${baseName}`);
                console.log(`    - Property (offset): '${offset}'`);
                console.log(`    - Value: '${val}'`);

                if (offset === "__proto__") {
                    console.log(`    - INFO: This step is traversing up to the prototype.`);
                }
                
                if (base === Object.prototype && offset === 'polluted') {
                    console.error(`\n---> CRITICAL: PROTOTYPE POLLUTION DETECTED!`);
                    console.error(`     Object.prototype.polluted is being set to "${val}"`);
                    console.error(`     Originating from string: "${originalPollutingString}"\n`);
                }
            }

            return { base: base, offset: offset, val: val };
        }
    }

    sandbox.addAnalysis(new DsetPollutionAnalysis());

})(J$);